"use client";

import Link from "next/link";
import { useState } from "react";

export default function Resumes() {
  const [loading, setLoading] = useState(false);
  const [generated, setGenerated] = useState(false);

  const handleGenerate = () => {
    setLoading(true);
    // Simulate FastAPI backend generation (PDF/DOCX)
    setTimeout(() => {
      setLoading(false);
      setGenerated(true);
    }, 2500);
  };

  const handleDownload = (format: "pdf" | "docx") => {
    // Generate a mock blob to simulate a real file download as per the plan
    const content = `Mock ${format.toUpperCase()} Resume Content generated by CareerForge AI`;
    const blob = new Blob([content], { type: format === 'pdf' ? 'application/pdf' : 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `resume_generated.${format}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-background via-zinc-50 to-zinc-100 dark:from-background dark:via-zinc-900 dark:to-zinc-950 text-zinc-900 dark:text-zinc-100 p-4 lg:p-12 relative overflow-hidden">
      
      {/* Background gradients */}
      <div className="absolute top-1/4 -left-32 w-96 h-96 bg-primary rounded-full mix-blend-multiply filter blur-[100px] opacity-10 animate-pulse-slow pointer-events-none"></div>

      <div className="max-w-6xl mx-auto space-y-8 relative z-10 animate-fade-in-up">
        
        {/* Navigation */}
        <nav className="flex items-center justify-between glass-card px-6 py-4 rounded-2xl mb-8">
          <div className="font-bold text-xl tracking-tight text-primary">CareerForge AI</div>
          <div className="flex items-center gap-6 text-sm font-medium">
            <Link href="/" className="text-zinc-500 hover:text-primary transition-colors">Home</Link>
            <Link href="/dashboard" className="text-zinc-500 hover:text-primary transition-colors">Dashboard</Link>
          </div>
        </nav>

        {/* Header */}
        <header className="flex justify-between items-end border-b border-zinc-200/50 dark:border-zinc-800/50 pb-4">
          <div>
            <h1 className="text-4xl lg:text-5xl font-extrabold tracking-tight bg-gradient-to-r from-zinc-900 to-zinc-500 dark:from-zinc-100 dark:to-zinc-500 bg-clip-text text-transparent">AI Resume Generator</h1>
            <p className="text-zinc-500 dark:text-zinc-400 mt-2 text-lg">Truth-Verified Document Generation tailored to ATS requirements.</p>
          </div>
        </header>

        {/* Builder UI */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8">
          
          <section className="space-y-6">
            <div className="glass-card p-8 rounded-3xl">
              <h2 className="font-bold text-2xl mb-6 tracking-tight">Configuration</h2>
              
              <div className="space-y-6">
                <div>
                  <label className="block text-sm font-semibold text-zinc-700 dark:text-zinc-300 mb-2">Target Opportunity</label>
                  <select className="w-full p-3 rounded-xl border border-zinc-300 dark:border-zinc-700 bg-white/50 dark:bg-zinc-900/50 focus:ring-2 focus:ring-primary focus:border-primary outline-none transition-all">
                    <option>Senior Frontend Engineer - Google</option>
                    <option>Backend Engineer - Stripe</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-semibold text-zinc-700 dark:text-zinc-300 mb-2">Template Style</label>
                  <select className="w-full p-3 rounded-xl border border-zinc-300 dark:border-zinc-700 bg-white/50 dark:bg-zinc-900/50 focus:ring-2 focus:ring-primary focus:border-primary outline-none transition-all">
                    <option>Modern ATS (Standard)</option>
                    <option>Academic CV</option>
                  </select>
                </div>
              </div>

              <button 
                onClick={handleGenerate}
                disabled={loading}
                className="w-full mt-8 py-4 px-4 bg-primary text-primary-foreground font-semibold rounded-xl hover:bg-primary/90 shadow-lg shadow-primary/30 transition-all hover:-translate-y-0.5 disabled:opacity-50 disabled:hover:translate-y-0 relative overflow-hidden"
              >
                {loading ? (
                   <span className="flex items-center justify-center">
                     <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                     Compiling Document...
                   </span>
                ) : "Generate Truth-Verified Resume"}
              </button>
            </div>
          </section>

          <section>
            <div className="glass-card p-8 h-full min-h-[450px] rounded-3xl flex flex-col items-center justify-center text-center relative overflow-hidden">
              {!generated && !loading && (
                <div className="text-zinc-400">
                  <div className="w-20 h-20 bg-zinc-100 dark:bg-zinc-800 rounded-full flex items-center justify-center mx-auto mb-4 border border-zinc-200 dark:border-zinc-700">
                    <svg className="w-10 h-10 opacity-50" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                  </div>
                  <p className="font-medium">Document Preview Area</p>
                  <p className="text-sm mt-1">Configure and generate to view your ATS resume.</p>
                </div>
              )}

              {loading && (
                <div className="animate-pulse space-y-6 w-full px-12">
                  <div className="h-32 bg-zinc-200 dark:bg-zinc-800 rounded-xl w-full mx-auto"></div>
                  <div className="h-4 bg-zinc-200 dark:bg-zinc-800 rounded w-3/4 mx-auto"></div>
                  <div className="h-4 bg-zinc-200 dark:bg-zinc-800 rounded w-1/2 mx-auto"></div>
                </div>
              )}

              {generated && (
                <div className="animate-fade-in-up w-full">
                  <div className="w-32 h-40 bg-white dark:bg-zinc-900 border-2 border-primary/20 rounded-lg mb-6 mx-auto shadow-xl flex items-center justify-center relative group overflow-hidden">
                    <span className="text-sm font-bold text-zinc-300 dark:text-zinc-700 absolute top-4 left-4">PDF</span>
                    <div className="w-12 h-1 bg-zinc-200 dark:bg-zinc-700 rounded absolute top-12 left-4"></div>
                    <div className="w-16 h-1 bg-zinc-200 dark:bg-zinc-700 rounded absolute top-16 left-4"></div>
                    <div className="w-24 h-1 bg-zinc-200 dark:bg-zinc-700 rounded absolute top-20 left-4"></div>
                    
                    <div className="absolute inset-0 bg-primary/10 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity backdrop-blur-sm">
                       <button onClick={() => handleDownload('pdf')} className="p-2 bg-primary text-white rounded-full shadow-lg">
                          <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                       </button>
                    </div>
                  </div>
                  <h3 className="font-extrabold text-2xl text-transparent bg-clip-text bg-gradient-to-r from-primary to-blue-600 mb-2">Generation Complete!</h3>
                  <p className="text-zinc-500 text-sm mb-6">Your ATS-optimized resume is ready.</p>
                  
                  <div className="flex flex-col sm:flex-row gap-4 justify-center">
                    <button 
                      onClick={() => handleDownload('pdf')}
                      className="px-6 py-3 bg-primary text-white rounded-xl font-semibold hover:bg-primary/90 transition-all shadow-lg shadow-primary/25 hover:-translate-y-0.5 flex items-center justify-center gap-2"
                    >
                      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                      Download PDF
                    </button>
                    <button 
                      onClick={() => handleDownload('docx')}
                      className="px-6 py-3 bg-white dark:bg-zinc-800 text-zinc-900 dark:text-white rounded-xl font-semibold border border-zinc-200 dark:border-zinc-700 hover:bg-zinc-50 dark:hover:bg-zinc-700 transition-all shadow-sm hover:-translate-y-0.5 flex items-center justify-center gap-2"
                    >
                      <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                      Download DOCX
                    </button>
                  </div>
                </div>
              )}
            </div>
          </section>

        </div>
      </div>
    </main>
  );
}
